import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import {
  TrendingUp,
  Target,
  Users,
  Megaphone,
  Zap,
  Shield,
  Sparkles,
  ArrowUpRight,
  Info,
  ArrowUp,
  ArrowDown,
  Minus,
  Inbox,
} from "lucide-react";
import { cn } from "@/lib/utils";
import todayData from "@/data/score-today.json";
import lastWeekData from "@/data/score-last-week.json";

export const Route = createFileRoute("/score")({
  head: () => ({
    meta: [
      { title: "Revenue DNA Score — SideKick" },
      {
        name: "description",
        content:
          "See your Revenue DNA Score from 0 to 100, broken down by clarity, traction, positioning, distribution, retention and brand criteria.",
      },
    ],
  }),
  component: ScorePage,
});

type Criterion = {
  key: string;
  label: string;
  description: string;
  icon: typeof Target;
  weight: number; // contribution weight
};

const CRITERIA_META: Criterion[] = [
  {
    key: "InMail",
    label: "InMail",
    description: "Clients generated by the InMail medium.",
    icon: Target,
    weight: 40,
  },
  {
    key: "Publication",
    label: "Publication",
    description: "Clients generated by Publications.",
    icon: TrendingUp,
    weight: 20,
  },
  {
    key: "Cold messages",
    label: "Cold messages",
    description: "Clients generated by Cold messages.",
    icon: Users,
    weight: 40,
  },
  {
    key: "distribution",
    label: "distribution",
    description: "Repeatable channels generating qualified pipeline each week.",
    icon: Megaphone,
    weight: 18,
  },
  {
    key: "velocity",
    label: "velocity",
    description: "Speed from idea → experiment → learning in your GTM motion.",
    icon: Zap,
    weight: 12,
  },
  {
    key: "retention",
    label: "retention",
    description: "Customer retention, NRR and account expansion signals.",
    icon: Shield,
    weight: 10,
  },
  {
    key: "brand",
    label: "brand",
    description: "Strength of public thought leadership and market POV.",
    icon: Sparkles,
    weight: 7,
  },
];

const todayScores = todayData.scores as unknown as Record<string, unknown>;
const lastWeekScores = lastWeekData.scores as unknown as Record<string, unknown>;
const todayDate = todayData.date;
const lastWeekDate = lastWeekData.date;

// "New forms" is not a percentage: it counts inbound contacts and represents
// overall performance. Shown as a separate KPI and excluded from the breakdown.
const NEW_FORMS_KEY = "New forms";
const PUBLICATION_KEY = "Publication";
export const PUBLICATION_FORMATS = ["text", "carousel", "video", "image", "poll"] as const;
export type PublicationFormat = (typeof PUBLICATION_FORMATS)[number];

function getScore(scores: Record<string, unknown>, key: string): number {
  const v = scores[key];
  if (typeof v === "number") return v;
  if (v && typeof v === "object") {
    const vals = Object.values(v as Record<string, number>);
    return vals.length ? Math.round(vals.reduce((s, n) => s + n, 0) / vals.length) : 0;
  }
  return 0;
}
function getFormats(scores: Record<string, unknown>): Record<PublicationFormat, number> {
  const v = scores[PUBLICATION_KEY];
  const out = {} as Record<PublicationFormat, number>;
  for (const f of PUBLICATION_FORMATS) {
    out[f] = v && typeof v === "object" ? ((v as Record<string, number>)[f] ?? 0) : 0;
  }
  return out;
}

const newFormsToday = (todayScores[NEW_FORMS_KEY] as number) ?? 0;
const newFormsLastWeek = (lastWeekScores[NEW_FORMS_KEY] as number) ?? 0;
const todayPubFormats = getFormats(todayScores);
const lastWeekPubFormats = getFormats(lastWeekScores);

// Solo incluir criterios presentes en el JSON de hoy
const CRITERIA = CRITERIA_META.filter((c) => c.key in todayScores && c.key !== NEW_FORMS_KEY).map((c) => ({
  ...c,
  score: getScore(todayScores, c.key),
  previousScore: getScore(lastWeekScores, c.key),
}));

function tierFor(score: number) {
  if (score >= 85) return { label: "Category Leader", tone: "from-emerald-400 to-teal-300" };
  if (score >= 70) return { label: "Scaling", tone: "from-primary to-accent" };
  if (score >= 55) return { label: "Emerging", tone: "from-accent to-sky-300" };
  if (score >= 40) return { label: "Forming", tone: "from-amber-400 to-orange-400" };
  return { label: "Early Signal", tone: "from-rose-400 to-orange-400" };
}

function Delta({ current, previous, size = "sm" }: { current: number; previous: number; size?: "sm" | "lg" }) {
  const diff = current - previous;
  const Icon = diff > 0 ? ArrowUp : diff < 0 ? ArrowDown : Minus;
  const tone =
    diff > 0
      ? "text-emerald-400 bg-emerald-400/10 border-emerald-400/20"
      : diff < 0
        ? "text-rose-400 bg-rose-400/10 border-rose-400/20"
        : "text-muted-foreground bg-white/5 border-glass-border";
  const text = diff === 0 ? "0" : `${diff > 0 ? "+" : ""}${diff}`;
  const dims = size === "lg" ? "px-2.5 py-1 text-sm" : "px-2 py-0.5 text-[11px]";
  const iconSize = size === "lg" ? "h-3.5 w-3.5" : "h-3 w-3";
  return (
    <span
      className={cn("inline-flex items-center gap-1 rounded-full border font-medium tabular-nums", dims, tone)}
      title="vs. last week"
    >
      <Icon className={iconSize} strokeWidth={3} />
      {text}
    </span>
  );
}

function ScorePage() {
  const [hovered, setHovered] = useState<string | null>(null);

  const overall = useMemo(() => {
    const totalWeight = CRITERIA.reduce((s, c) => s + c.weight, 0);
    const weighted = CRITERIA.reduce((s, c) => s + c.score * c.weight, 0);
    return totalWeight > 0 ? Math.round(weighted / totalWeight) : 0;
  }, [todayDate]);

  const previousOverall = useMemo(() => {
    const totalWeight = CRITERIA.reduce((s, c) => s + c.weight, 0);
    const weighted = CRITERIA.reduce((s, c) => s + c.previousScore * c.weight, 0);
    return totalWeight > 0 ? Math.round(weighted / totalWeight) : 0;
  }, [lastWeekDate]);

  const tier = tierFor(overall);

  // Ring geometry
  const R = 110;
  const C = 2 * Math.PI * R;
  const offset = C - (overall / 100) * C;

  return (
    <main className="relative min-h-screen overflow-hidden">
      <div className="pointer-events-none absolute inset-0 grid-bg" aria-hidden />
      <div
        className="pointer-events-none absolute -top-40 left-1/2 h-[520px] w-[820px] -translate-x-1/2 rounded-full opacity-60 blur-3xl"
        style={{ background: "var(--gradient-primary)", filter: "blur(120px)" }}
        aria-hidden
      />

      <div className="relative mx-auto max-w-6xl px-5 py-14 md:py-20">
        {/* Header */}
        <div className="mb-10 flex flex-col items-start justify-between gap-4 md:flex-row md:items-end">
          <div className="animate-fade-up">
            <div className="inline-flex items-center gap-2 rounded-full glass px-3 py-1 text-xs text-muted-foreground">
              <Sparkles className="h-3.5 w-3.5 text-primary" />
              Revenue DNA Diagnostic
            </div>
            <h1 className="mt-4 text-4xl font-semibold tracking-tight text-gradient md:text-5xl">
              Your Revenue DNA Score
            </h1>
            <p className="mt-2 max-w-xl text-sm text-muted-foreground md:text-base">
              A single 0–100 score synthesizing seven weighted criteria that determine whether your go-to-market is
              ready to compound.
            </p>
          </div>
          <Link
            to="/improve"
            className="group inline-flex items-center gap-2 rounded-xl bg-gradient-primary px-5 py-2.5 text-sm font-medium text-primary-foreground shadow-glow transition hover:scale-[1.02]"
          >
            Improve my score
            <ArrowUpRight className="h-4 w-4 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5" />
          </Link>
        </div>

        {/* New forms — overall performance (count, not percentage) */}
        <section className="mb-6 glass-strong rounded-3xl p-6 md:p-8 animate-fade-up">
          <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
            <div className="flex items-center gap-4">
              <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-gradient-primary/20 text-primary">
                <Inbox className="h-6 w-6" />
              </div>
              <div>
                <div className="text-xs uppercase tracking-widest text-muted-foreground">Overall performance</div>
                <div className="mt-1 text-sm font-medium">New forms</div>
                <p className="mt-0.5 max-w-md text-xs text-muted-foreground">
                  Inbound contacts through our forms. Aggregate metric that reflects overall performance (not a
                  percentage).
                </p>
              </div>
            </div>
            <div className="flex items-baseline gap-3">
              <span className="text-4xl font-semibold text-gradient-primary tabular-nums md:text-5xl">
                {newFormsToday}
              </span>
              <Delta current={newFormsToday} previous={newFormsLastWeek} size="lg" />
              <span className="text-[11px] uppercase tracking-widest text-muted-foreground">
                vs. last week ({newFormsLastWeek})
              </span>
            </div>
          </div>
        </section>

        <div className="grid gap-6 lg:grid-cols-[1fr_1.4fr]">
          {/* Score ring */}
          <section className="glass-strong relative flex flex-col items-center justify-center rounded-3xl p-8 animate-fade-up">
            <div className="relative">
              <svg width="260" height="260" viewBox="0 0 260 260" className="-rotate-90">
                <defs>
                  <linearGradient id="scoreGrad" x1="0" y1="0" x2="1" y2="1">
                    <stop offset="0%" stopColor="oklch(0.74 0.18 290)" />
                    <stop offset="60%" stopColor="oklch(0.78 0.16 220)" />
                    <stop offset="100%" stopColor="oklch(0.82 0.14 200)" />
                  </linearGradient>
                </defs>
                <circle cx="130" cy="130" r={R} fill="none" stroke="oklch(1 0 0 / 0.08)" strokeWidth="14" />
                <circle
                  cx="130"
                  cy="130"
                  r={R}
                  fill="none"
                  stroke="url(#scoreGrad)"
                  strokeWidth="14"
                  strokeLinecap="round"
                  strokeDasharray={C}
                  strokeDashoffset={offset}
                  style={{ transition: "stroke-dashoffset 1.2s cubic-bezier(.22,1,.36,1)" }}
                />
              </svg>
              <div className="absolute inset-0 flex flex-col items-center justify-center">
                <div className="text-6xl font-semibold text-gradient-primary tabular-nums">{overall}</div>
                <div className="mt-1 text-xs uppercase tracking-widest text-muted-foreground">/ 100</div>
                <div className="mt-3">
                  <Delta current={overall} previous={previousOverall} size="lg" />
                </div>
                <div className="mt-1 text-[10px] uppercase tracking-widest text-muted-foreground">
                  vs. last week ({previousOverall})
                </div>
              </div>
            </div>

            <div
              className={cn(
                "mt-6 rounded-full bg-gradient-to-r px-4 py-1.5 text-xs font-medium text-primary-foreground",
                tier.tone,
              )}
            >
              {tier.label}
            </div>

            <p className="mt-6 max-w-xs text-center text-xs text-muted-foreground">
              Weighted across 7 GTM criteria. Hover any criterion to see how it shapes the overall score.
            </p>
          </section>

          {/* Criteria breakdown */}
          <section className="glass-strong rounded-3xl p-6 md:p-8 animate-fade-up">
            <div className="mb-5 flex items-center justify-between">
              <h2 className="text-lg font-semibold">Score breakdown</h2>
              <div className="inline-flex items-center gap-1.5 text-xs text-muted-foreground">
                <Info className="h-3.5 w-3.5" />
                Weighted contribution shown on the right
              </div>
            </div>

            <ul className="space-y-3">
              {CRITERIA.map((c) => {
                const Icon = c.icon;
                const isHover = hovered === c.key;
                return (
                  <li
                    key={c.key}
                    onMouseEnter={() => setHovered(c.key)}
                    onMouseLeave={() => setHovered(null)}
                    className={cn(
                      "group relative rounded-2xl border border-glass-border bg-glass p-4 transition",
                      isHover && "border-primary/40 shadow-glow",
                    )}
                  >
                    <div className="flex items-center gap-4">
                      <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-gradient-primary/20 text-primary">
                        <Icon className="h-5 w-5" />
                      </div>

                      <div className="min-w-0 flex-1">
                        <div className="flex items-baseline justify-between gap-3">
                          <div className="truncate text-sm font-medium">{c.label}</div>
                          <div className="flex items-baseline gap-2 tabular-nums">
                            <span className="text-base font-semibold text-foreground">{c.score}</span>
                            <span className="text-xs text-muted-foreground">/100</span>
                            <Delta current={c.score} previous={c.previousScore} />
                          </div>
                        </div>
                        <p className="mt-0.5 text-xs text-muted-foreground">{c.description}</p>

                        {/* Bar with last-week marker */}
                        <div className="relative mt-3 h-1.5 w-full overflow-hidden rounded-full bg-white/5">
                          <div
                            className="h-full rounded-full bg-gradient-primary transition-all duration-700"
                            style={{ width: `${c.score}%` }}
                          />
                          <div
                            className="absolute top-1/2 h-3 w-px -translate-y-1/2 bg-white/40"
                            style={{ left: `${c.previousScore}%` }}
                            title={`Last week: ${c.previousScore}`}
                          />
                        </div>
                        <div className="mt-1 text-[10px] text-muted-foreground">
                          Last week: <span className="tabular-nums">{c.previousScore}</span>
                        </div>

                        {c.key === PUBLICATION_KEY && (
                          <div className="mt-3 grid grid-cols-2 gap-x-4 gap-y-1.5 sm:grid-cols-5">
                            {PUBLICATION_FORMATS.map((f) => {
                              const v = todayPubFormats[f];
                              const prev = lastWeekPubFormats[f];
                              return (
                                <div key={f} className="min-w-0">
                                  <div className="flex items-baseline justify-between gap-1.5">
                                    <span className="truncate text-[10px] uppercase tracking-wider text-muted-foreground">
                                      {f}
                                    </span>
                                    <span className="text-[11px] font-medium tabular-nums">{v}</span>
                                  </div>
                                  <div className="relative mt-1 h-1 w-full overflow-hidden rounded-full bg-white/5">
                                    <div
                                      className="h-full rounded-full bg-gradient-primary"
                                      style={{ width: `${v}%` }}
                                    />
                                    <div
                                      className="absolute top-1/2 h-2 w-px -translate-y-1/2 bg-white/40"
                                      style={{ left: `${prev}%` }}
                                      title={`Last week: ${prev}`}
                                    />
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        )}
                      </div>

                      <div className="hidden w-14 shrink-0 text-right md:block">
                        <div className="text-[11px] uppercase tracking-wider text-muted-foreground">weight</div>
                        <div className="text-sm font-medium tabular-nums">{c.weight}%</div>
                      </div>
                    </div>
                  </li>
                );
              })}
            </ul>
          </section>
        </div>

        {/* Insight footer */}
        <section className="mt-6 glass-strong rounded-3xl p-6 md:p-8 animate-fade-up">
          <h3 className="text-sm uppercase tracking-widest text-muted-foreground">What this score means</h3>
          <p className="mt-2 max-w-3xl text-sm leading-relaxed text-foreground/90 md:text-base">
            Your Revenue DNA scores <span className="font-semibold text-gradient-primary">{overall}/100</span> — placing
            you in the <span className="font-medium">{tier.label}</span> tier. Your sharpest edge is{" "}
            <span className="font-medium">Positioning Clarity</span>; the biggest unlock for the next 90 days is{" "}
            <span className="font-medium">Distribution Engine</span>, which currently caps how fast everything else can
            compound.
          </p>
        </section>
      </div>
    </main>
  );
}
